from datetime import time as time_object

#AUGUST
prefajr_least_before = time_object(hour=0, minute=0)
prefajr_most_before = time_object(hour=3, minute=33) #i.e. between  and 
fajr_least_before = time_object(hour=3, minute=33) 
fajr_most_before = time_object(hour=6, minute=0)
prezuhr_least_before = time_object(hour=6, minute=0)
prezuhr_most_before = time_object(hour=12, minute=9)
zuhr_least_before = time_object(hour=12, minute=9)
zuhr_most_before = time_object(hour=14, minute=20)
preasr_least_before = time_object(hour=14, minute=20)
preasr_most_before = time_object(hour=15, minute=59)
asr_least_before = time_object(hour=15, minute=59)
asr_most_before = time_object(hour=17, minute=55)
premaghrib_least_before = time_object(hour=17, minute=55)
premaghrib_most_before = time_object(hour=19, minute=7)
maghrib_least_before = time_object(hour=19, minute=7)
maghrib_most_before = time_object(hour=20, minute=30)
preisha_least_before = time_object(hour=20, minute=30)
preisha_most_before = time_object(hour=20, minute=50)
isha_least_before = time_object(hour=20, minute=50)
isha_most_before = time_object(hour=23, minute=59)

#goes to 
prefajr_least_after = time_object(hour=0, minute=0)
prefajr_most_after = time_object(hour=4, minute=10) 
fajr_least_after = time_object(hour=4, minute=10)
fajr_most_after = time_object(hour=6, minute=12)
prezuhr_least_after = time_object(hour=6, minute=12)
prezuhr_most_after = time_object(hour=12, minute=3)
zuhr_least_after = time_object(hour=12, minute=3)
zuhr_most_after = time_object(hour=14, minute=25) #i.e. between  and 
preasr_least_after = time_object(hour=14, minute=25)
preasr_most_after = time_object(hour=15, minute=41)
asr_least_after = time_object(hour=15, minute=41)
asr_most_after = time_object(hour=17, minute=44)
premaghrib_least_after = time_object(hour=17, minute=44)
premaghrib_most_after = time_object(hour=18, minute=31)
maghrib_least_after = time_object(hour=18, minute=31)
maghrib_most_after = time_object(hour=20, minute=10)
preisha_least_after = time_object(hour=20, minute=10)
preisha_most_after = time_object(hour=20, minute=15)
isha_least_after = time_object(hour=20, minute=15)
isha_most_after = time_object(hour=23, minute=59)