from datetime import time as time_object

#DECEMBER
prefajr_least_before = time_object(hour=0, minute=0)
prefajr_most_before = time_object(hour=5, minute=24) #i.e. between  and 
fajr_least_before = time_object(hour=5, minute=26) 
fajr_most_before = time_object(hour=6, minute=50)
prezuhr_least_before = time_object(hour=6, minute=50)
prezuhr_most_before = time_object(hour=11, minute=52)
zuhr_least_before = time_object(hour=11, minute=52)
zuhr_most_before = time_object(hour=14, minute=16)
preasr_least_before = time_object(hour=14, minute=16)
preasr_most_before = time_object(hour=14, minute=35)
asr_least_before = time_object(hour=14, minute=35)
asr_most_before = time_object(hour=16, minute=35)
premaghrib_least_before = time_object(hour=16, minute=35)
premaghrib_most_before = time_object(hour=16, minute=49)
maghrib_least_before = time_object(hour=16, minute=49)
maghrib_most_before = time_object(hour=18, minute=34)
preisha_least_before = time_object(hour=18, minute=34)
preisha_most_before = time_object(hour=18, minute=39)
isha_least_before = time_object(hour=18, minute=39)
isha_most_before = time_object(hour=23, minute=59)

#goes to 
prefajr_least_after = time_object(hour=0, minute=0)
prefajr_most_after = time_object(hour=5, minute=41) 
fajr_least_after = time_object(hour=5, minute=41)
fajr_most_after = time_object(hour=6, minute=59)
prezuhr_least_after = time_object(hour=6, minute=59)
prezuhr_most_after = time_object(hour=12, minute=10)
zuhr_least_after = time_object(hour=12, minute=10)
zuhr_most_after = time_object(hour=14, minute=18) #i.e. between  and 
preasr_least_after = time_object(hour=14, minute=18)
preasr_most_after = time_object(hour=14, minute=42)
asr_least_after = time_object(hour=14, minute=42)
asr_most_after = time_object(hour=16, minute=45)
premaghrib_least_after = time_object(hour=16, minute=45)
premaghrib_most_after = time_object(hour=17, minute=0)
maghrib_least_after = time_object(hour=17, minute=0)
maghrib_most_after = time_object(hour=18, minute=45)
preisha_least_after = time_object(hour=18, minute=45)
preisha_most_after = time_object(hour=18, minute=55)
isha_least_after = time_object(hour=18, minute=55)
isha_most_after = time_object(hour=23, minute=59)