from datetime import time as time_object

#FEBRUARY
prefajr_least_before = time_object(hour=0, minute=0)
prefajr_most_before = time_object(hour=5, minute=35) #i.e. between  and 
fajr_least_before = time_object(hour=5, minute=35) 
fajr_most_before = time_object(hour=6, minute=45)
prezuhr_least_before = time_object(hour=6, minute=45)
prezuhr_most_before = time_object(hour=12, minute=35)
zuhr_least_before = time_object(hour=12, minute=35)
zuhr_most_before = time_object(hour=14, minute=20)
preasr_least_before = time_object(hour=14, minute=20)
preasr_most_before = time_object(hour=15, minute=8)
asr_least_before = time_object(hour=15, minute=8)
asr_most_before = time_object(hour=16, minute=50)
premaghrib_least_before = time_object(hour=16, minute=50)
premaghrib_most_before = time_object(hour=17, minute=30)
maghrib_least_before = time_object(hour=17, minute=30)
maghrib_most_before = time_object(hour=19, minute=10)
preisha_least_before = time_object(hour=19, minute=10)
preisha_most_before = time_object(hour=19, minute=16)
isha_least_before = time_object(hour=19, minute=16)
isha_most_before = time_object(hour=23, minute=59)

#goes to 
prefajr_least_after = time_object(hour=0, minute=0)
prefajr_most_after = time_object(hour=5, minute=8) 
fajr_least_after = time_object(hour=5, minute=8)
fajr_most_after = time_object(hour=6, minute=34)
prezuhr_least_after = time_object(hour=6, minute=34)
prezuhr_most_after = time_object(hour=12, minute=35)
zuhr_least_after = time_object(hour=12, minute=35)
zuhr_most_after = time_object(hour=14, minute=20) #i.e. between  and 
preasr_least_after = time_object(hour=14, minute=20)
preasr_most_after = time_object(hour=15, minute=28)
asr_least_after = time_object(hour=15, minute=28)
asr_most_after = time_object(hour=17, minute=15)
premaghrib_least_after = time_object(hour=17, minute=15)
premaghrib_most_after = time_object(hour=17, minute=59)
maghrib_least_after = time_object(hour=17, minute=59)
maghrib_most_after = time_object(hour=19, minute=43)
preisha_least_after = time_object(hour=19, minute=43)
preisha_most_after = time_object(hour=19, minute=51)
isha_least_after = time_object(hour=19, minute=51)
isha_most_after = time_object(hour=23, minute=59)