from datetime import time as time_object

#MARCH
prefajr_least_before = time_object(hour=0, minute=0)
prefajr_most_before = time_object(hour=5, minute=7) #i.e. between  and 
fajr_least_before = time_object(hour=5, minute=7) 
fajr_most_before = time_object(hour=6, minute=39)
prezuhr_least_before = time_object(hour=6, minute=39)
prezuhr_most_before = time_object(hour=12, minute=30)
zuhr_least_before = time_object(hour=12, minute=30)
zuhr_most_before = time_object(hour=14, minute=25)
preasr_least_before = time_object(hour=14, minute=25)
preasr_most_before = time_object(hour=15, minute=30)
asr_least_before = time_object(hour=15, minute=30)
asr_most_before = time_object(hour=16, minute=59)
premaghrib_least_before = time_object(hour=16, minute=59)
premaghrib_most_before = time_object(hour=17, minute=59)
maghrib_least_before = time_object(hour=17, minute=59)
maghrib_most_before = time_object(hour=19, minute=45)
preisha_least_before = time_object(hour=19, minute=45)
preisha_most_before = time_object(hour=19, minute=55)
isha_least_before = time_object(hour=19, minute=55)
isha_most_before = time_object(hour=23, minute=59)

#goes to 
prefajr_least_after = time_object(hour=0, minute=0)
prefajr_most_after = time_object(hour=4, minute=22) 
fajr_least_after = time_object(hour=4, minute=22)
fajr_most_after = time_object(hour=6, minute=25)
prezuhr_least_after = time_object(hour=6, minute=25)
prezuhr_most_after = time_object(hour=12, minute=15)
zuhr_least_after = time_object(hour=12, minute=15)
zuhr_most_after = time_object(hour=14, minute=15) #i.e. between  and 
preasr_least_after = time_object(hour=14, minute=15)
preasr_most_after = time_object(hour=15, minute=42)
asr_least_after = time_object(hour=15, minute=42)
asr_most_after = time_object(hour=17, minute=5)
premaghrib_least_after = time_object(hour=17, minute=5)
premaghrib_most_after = time_object(hour=18, minute=25)
maghrib_least_after = time_object(hour=18, minute=25)
maghrib_most_after = time_object(hour=20, minute=0)
preisha_least_after = time_object(hour=20, minute=0)
preisha_most_after = time_object(hour=20, minute=15)
isha_least_after = time_object(hour=20, minute=15)
isha_most_after = time_object(hour=23, minute=59)