from datetime import time as time_object

#MAY
prefajr_least_before = time_object(hour=0, minute=0)
prefajr_most_before = time_object(hour=3, minute=34) #i.e. between  and 
fajr_least_before = time_object(hour=3, minute=34) 
fajr_most_before = time_object(hour=5, minute=36)
prezuhr_least_before = time_object(hour=5, minute=36)
prezuhr_most_before = time_object(hour=11, minute=59)
zuhr_least_before = time_object(hour=11, minute=59)
zuhr_most_before = time_object(hour=14, minute=10)
preasr_least_before = time_object(hour=14, minute=10)
preasr_most_before = time_object(hour=15, minute=45)
asr_least_before = time_object(hour=15, minute=45)
asr_most_before = time_object(hour=17, minute=10)
premaghrib_least_before = time_object(hour=17, minute=10)
premaghrib_most_before = time_object(hour=18, minute=59)
maghrib_least_before = time_object(hour=18, minute=59)
maghrib_most_before = time_object(hour=19, minute=59)
preisha_least_before = time_object(hour=19, minute=59)
preisha_most_before = time_object(hour=20, minute=25)
isha_least_before = time_object(hour=20, minute=25)
isha_most_before = time_object(hour=23, minute=59)

#goes to 
prefajr_least_after = time_object(hour=0, minute=0)
prefajr_most_after = time_object(hour=3, minute=2) 
fajr_least_after = time_object(hour=3, minute=2)
fajr_most_after = time_object(hour=5, minute=26)
prezuhr_least_after = time_object(hour=5, minute=26)
prezuhr_most_after = time_object(hour=12, minute=0)
zuhr_least_after = time_object(hour=12, minute=0)
zuhr_most_after = time_object(hour=14, minute=15) #i.e. between  and 
preasr_least_after = time_object(hour=14, minute=15)
preasr_most_after = time_object(hour=15, minute=49)
asr_least_after = time_object(hour=15, minute=49)
asr_most_after = time_object(hour=17, minute=20)
premaghrib_least_after = time_object(hour=17, minute=20)
premaghrib_most_after = time_object(hour=19, minute=20)
maghrib_least_after = time_object(hour=19, minute=25)
maghrib_most_after = time_object(hour=20, minute=20)
preisha_least_after = time_object(hour=20, minute=20)
preisha_most_after = time_object(hour=21, minute=5)
isha_least_after = time_object(hour=21, minute=5)
isha_most_after = time_object(hour=23, minute=59)