from datetime import time as time_object

#NOVEMBER
prefajr_least_before = time_object(hour=0, minute=0)
prefajr_most_before = time_object(hour=5, minute=0) #i.e. between  and 
fajr_least_before = time_object(hour=5, minute=0) 
fajr_most_before = time_object(hour=6, minute=30)
prezuhr_least_before = time_object(hour=6, minute=30)
prezuhr_most_before = time_object(hour=11, minute=48)
zuhr_least_before = time_object(hour=11, minute=48)
zuhr_most_before = time_object(hour=14, minute=10)
preasr_least_before = time_object(hour=14, minute=10)
preasr_most_before = time_object(hour=14, minute=44)
asr_least_before = time_object(hour=14, minute=44)
asr_most_before = time_object(hour=16, minute=45)
premaghrib_least_before = time_object(hour=16, minute=45)
premaghrib_most_before = time_object(hour=17, minute=7)
maghrib_least_before = time_object(hour=17, minute=7)
maghrib_most_before = time_object(hour=18, minute=50)
preisha_least_before = time_object(hour=18, minute=50)
preisha_most_before = time_object(hour=18, minute=55)
isha_least_before = time_object(hour=18, minute=55)
isha_most_before = time_object(hour=23, minute=59)

#goes to 
prefajr_least_after = time_object(hour=0, minute=0)
prefajr_most_after = time_object(hour=5, minute=25) 
fajr_least_after = time_object(hour=5, minute=25)
fajr_most_after = time_object(hour=6, minute=50)
prezuhr_least_after = time_object(hour=6, minute=50)
prezuhr_most_after = time_object(hour=11, minute=55)
zuhr_least_after = time_object(hour=11, minute=55)
zuhr_most_after = time_object(hour=14, minute=16) #i.e. between  and 
preasr_least_after = time_object(hour=14, minute=16)
preasr_most_after = time_object(hour=14, minute=35)
asr_least_after = time_object(hour=14, minute=35)
asr_most_after = time_object(hour=16, minute=35)
premaghrib_least_after = time_object(hour=16, minute=35)
premaghrib_most_after = time_object(hour=16, minute=51)
maghrib_least_after = time_object(hour=16, minute=51)
maghrib_most_after = time_object(hour=18, minute=34)
preisha_least_after = time_object(hour=18, minute=34)
preisha_most_after = time_object(hour=18, minute=40)
isha_least_after = time_object(hour=18, minute=40)
isha_most_after = time_object(hour=23, minute=59)