from datetime import time as time_object

#OCTOBER
prefajr_least_before = time_object(hour=0, minute=0)
prefajr_most_before = time_object(hour=4, minute=33) #i.e. between  and 
fajr_least_before = time_object(hour=4, minute=33) 
fajr_most_before = time_object(hour=6, minute=20)
prezuhr_least_before = time_object(hour=6, minute=20)
prezuhr_most_before = time_object(hour=11, minute=55)
zuhr_least_before = time_object(hour=11, minute=55)
zuhr_most_before = time_object(hour=14, minute=15)
preasr_least_before = time_object(hour=14, minute=15)
preasr_most_before = time_object(hour=15, minute=13)
asr_least_before = time_object(hour=15, minute=13)
asr_most_before = time_object(hour=17, minute=14)
premaghrib_least_before = time_object(hour=17, minute=14)
premaghrib_most_before = time_object(hour=17, minute=52)
maghrib_least_before = time_object(hour=17, minute=52)
maghrib_most_before = time_object(hour=19, minute=9)
preisha_least_before = time_object(hour=19, minute=9)
preisha_most_before = time_object(hour=19, minute=11)
isha_least_before = time_object(hour=19, minute=11)
isha_most_before = time_object(hour=23, minute=59)

#goes to 
prefajr_least_after = time_object(hour=0, minute=0)
prefajr_most_after = time_object(hour=0, minute=0) 
fajr_least_after = time_object(hour=5, minute=0)
fajr_most_after = time_object(hour=6, minute=34)
prezuhr_least_after = time_object(hour=6, minute=34)
prezuhr_most_after = time_object(hour=11, minute=46)
zuhr_least_after = time_object(hour=11, minute=46)
zuhr_most_after = time_object(hour=14, minute=13) #i.e. between  and 
preasr_least_after = time_object(hour=14, minute=13)
preasr_most_after = time_object(hour=14, minute=45)
asr_least_after = time_object(hour=14, minute=45)
asr_most_after = time_object(hour=16, minute=45)
premaghrib_least_after = time_object(hour=16, minute=45)
premaghrib_most_after = time_object(hour=17, minute=10)
maghrib_least_after = time_object(hour=17, minute=10)
maghrib_most_after = time_object(hour=18, minute=45)
preisha_least_after = time_object(hour=18, minute=45)
preisha_most_after = time_object(hour=18, minute=55)
isha_least_after = time_object(hour=18, minute=55)
isha_most_after = time_object(hour=23, minute=59)