from datetime import time as time_object

#SEPTEMBER
prefajr_least_before = time_object(hour=0, minute=0)
prefajr_most_before = time_object(hour=4, minute=7) #i.e. between  and 
fajr_least_before = time_object(hour=4, minute=7) 
fajr_most_before = time_object(hour=6, minute=12)
prezuhr_least_before = time_object(hour=6, minute=12)
prezuhr_most_before = time_object(hour=12, minute=2)
zuhr_least_before = time_object(hour=12, minute=2)
zuhr_most_before = time_object(hour=14, minute=17)
preasr_least_before = time_object(hour=14, minute=17)
preasr_most_before = time_object(hour=15, minute=43)
asr_least_before = time_object(hour=15, minute=43)
asr_most_before = time_object(hour=17, minute=49)
premaghrib_least_before = time_object(hour=17, minute=49)
premaghrib_most_before = time_object(hour=18, minute=30)
maghrib_least_before = time_object(hour=18, minute=30)
maghrib_most_before = time_object(hour=20, minute=15)
preisha_least_before = time_object(hour=20, minute=15)
preisha_most_before = time_object(hour=20, minute=18)
isha_least_before = time_object(hour=20, minute=18)
isha_most_before = time_object(hour=23, minute=59)

#goes to 
prefajr_least_after = time_object(hour=0, minute=0)
prefajr_most_after = time_object(hour=4, minute=33) 
fajr_least_after = time_object(hour=4, minute=33)
fajr_most_after = time_object(hour=6, minute=19)
prezuhr_least_after = time_object(hour=6, minute=19)
prezuhr_most_after = time_object(hour=11, minute=58)
zuhr_least_after = time_object(hour=11, minute=58)
zuhr_most_after = time_object(hour=14, minute=13) #i.e. between  and 
preasr_least_after = time_object(hour=14, minute=13)
preasr_most_after = time_object(hour=15, minute=14)
asr_least_after = time_object(hour=15, minute=14)
asr_most_after = time_object(hour=17, minute=15)
premaghrib_least_after = time_object(hour=17, minute=15)
premaghrib_most_after = time_object(hour=17, minute=50)
maghrib_least_after = time_object(hour=17, minute=50)
maghrib_most_after = time_object(hour=19, minute=5)
preisha_least_after = time_object(hour=19, minute=5)
preisha_most_after = time_object(hour=19, minute=12)
isha_least_after = time_object(hour=19, minute=12)
isha_most_after = time_object(hour=23, minute=59)