ITEMS_PER_PAGE = 20
PHOTOS_PER_PAGE = 10
CRICKET_COMMENTS_PER_PAGE = 20
FANS_PER_PAGE = 100
STARS_PER_PAGE = 100
ADS_TO_APPROVE_PER_PAGE = 30
APPROVED_ADS_PER_PAGE = 20
MAX_ITEMS_PER_PAGE = 100
########################
WEEKLY_ECOMM_METRICS_HISTORY_LIMIT = 12
DAILY_ECOMM_METRICS_HISTORY_LIMIT = 60